
import { PokerSession } from '@/types/poker';

export const convertDatabaseSessionToPokerSession = (
  sessionData: any,
  tables: any[],
  hands: any[]
): PokerSession => {
  return {
    id: sessionData.id,
    gameType: sessionData.game_type || 'NLH',
    format: sessionData.format || 'Cash',
    location: sessionData.location || '',
    physicalLocation: sessionData.physical_location,
    tableName: sessionData.table_name,
    buyIn: sessionData.buy_in || 0,
    initialBuyIn: sessionData.initial_buy_in || sessionData.buy_in || 0,
    smallBlind: sessionData.small_blind || 0,
    bigBlind: sessionData.big_blind || 0,
    isOnline: sessionData.is_online,
    startingBB: sessionData.starting_bb,
    tournamentTypes: sessionData.tournament_types,
    isMultiDay: sessionData.is_multi_day,
    startTime: new Date(sessionData.start_time),
    endTime: sessionData.end_time ? new Date(sessionData.end_time) : undefined,
    cashOut: sessionData.cash_out,
    notes: sessionData.notes,
    isActive: sessionData.is_active,
    currentStatus: sessionData.current_status,
    sessionDuration: sessionData.session_duration,
    rebuys: sessionData.rebuys,
    rebuyAmount: sessionData.rebuy_amount,
    roi: sessionData.roi,
    itmRatioNumerator: sessionData.itm_ratio_numerator,
    itmRatioDenominator: sessionData.itm_ratio_denominator,
    tablesPlayed: sessionData.tables_played,
    tables: tables.map(table => ({
      id: table.id,
      name: table.table_name || '',
      format: table.table_type || 'Cash',
      gameType: table.game_format || 'NLH',
      location: table.location || sessionData.location || '',
      buyIn: table.buy_in || 0,
      initialBuyIn: table.buy_in || 0,
      smallBlind: table.stakes ? parseFloat(table.stakes.split('/')[0]) : undefined,
      bigBlind: table.stakes ? parseFloat(table.stakes.split('/')[1]) : undefined,
      startingBB: table.starting_stack,
      currentStack: table.current_stack,
      isActive: table.is_active,
      startTime: new Date(table.start_time),
      endTime: table.end_time ? new Date(table.end_time) : undefined,
      cashOut: table.cashout,
      rebuys: table.rebuys,
      rebuyAmount: table.rebuy_amount,
      bountyAmount: table.bounty_amount,
      finalPosition: table.final_position,
      notes: table.table_notes,
      session_id: table.session_id,
      hands: []
    })),
    hands: hands.map(hand => ({
      id: hand.id,
      tableId: hand.table_id,
      handNumber: hand.hand_number,
      position: hand.position,
      cards: hand.hole_cards || '',
      action: hand.preflop_action || '',
      holeCards: hand.hole_cards ? hand.hole_cards.split(',') : [],
      preflopAction: hand.preflop_action,
      flopCards: hand.flop_cards ? hand.flop_cards.split(',') : [],
      flopAction: hand.flop_action,
      turnCard: hand.turn_card,
      turnAction: hand.turn_action,
      riverCard: hand.river_card,
      riverAction: hand.river_action,
      showdownResult: hand.showdown_result,
      potSize: hand.pot_size,
      amountInvested: hand.amount_invested,
      amountWon: hand.amount_won,
      notes: hand.hand_notes,
      image: hand.hand_image,
      currencyType: hand.currency_type,
      createdAt: new Date(hand.created_at)
    }))
  };
};
