import { jsPDF } from 'jspdf';
import { format } from 'date-fns';
import type { FilterOptions } from '@/components/StatisticsFilterModal';

interface StatData {
  label: string;
  value: string;
}

interface ExportData {
  activeTab: string;
  stats: StatData[];
  filters: FilterOptions;
  userName?: string;
}

export const generateStatisticsPDF = (data: ExportData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  
  let currentY = margin;
  
  // Header - SessionMaster Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('SessionMaster', margin, currentY);
  currentY += 10;
  
  // My Statistics Title
  doc.setFontSize(16);
  doc.text('My Statistics', margin, currentY);
  currentY += 15;
  
  // Timeframe and Scope
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const timeframeText = data.filters.timeframeType === 'custom' 
    ? `Custom Range: ${data.filters.customStartDate ? format(data.filters.customStartDate, 'MMM dd, yyyy') : 'Not set'} - ${data.filters.customEndDate ? format(data.filters.customEndDate, 'MMM dd, yyyy') : 'Not set'}`
    : data.filters.timeframeValue;
  const scopeText = data.filters.gameScope === 'all' ? 'All Games' : 
                   data.filters.gameScope === 'cash' ? 'Cash Games' : 'Tournaments';
  
  doc.text(`Timeframe: ${timeframeText}`, margin, currentY);
  currentY += 7;
  doc.text(`Scope: ${scopeText}`, margin, currentY);
  currentY += 15;
  
  // Meta information
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  if (data.userName) {
    doc.text(`User: ${data.userName}`, margin, currentY);
    currentY += 5;
  }
  doc.text(`Generated: ${format(new Date(), 'MMM dd, yyyy \'at\' HH:mm')}`, margin, currentY);
  currentY += 5;
  doc.text('App Version: 1.0.0', margin, currentY);
  currentY += 20;
  
  // Active Tab Title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(`${data.activeTab} Statistics`, margin, currentY);
  currentY += 15;
  
  // Statistics in 2-column layout
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const columnWidth = contentWidth / 2;
  const leftColumnX = margin;
  const rightColumnX = margin + columnWidth + 10;
  let leftColumnY = currentY;
  let rightColumnY = currentY;
  
  data.stats.forEach((stat, index) => {
    const isLeftColumn = index % 2 === 0;
    const x = isLeftColumn ? leftColumnX : rightColumnX;
    const y = isLeftColumn ? leftColumnY : rightColumnY;
    
    // Label
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(stat.label, x, y);
    
    // Value with color coding
    doc.setFont('helvetica', 'bold');
    const value = stat.value;
    
    // Color based on value (green for positive, red for negative)
    if (value.includes('$') && (value.includes('-') || value.startsWith('-'))) {
      doc.setTextColor(220, 53, 69); // Red
    } else if (value.includes('$') || value.includes('%')) {
      doc.setTextColor(40, 167, 69); // Green
    } else {
      doc.setTextColor(33, 37, 41); // Dark gray
    }
    
    doc.text(value, x, y + 5);
    
    if (isLeftColumn) {
      leftColumnY += 18;
    } else {
      rightColumnY += 18;
    }
  });
  
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by SessionMaster', pageWidth / 2, footerY, { align: 'center' });
  
  // Generate filename
  const timeframeForFilename = data.filters.timeframeType === 'custom' ? 'Custom' : 
                              data.filters.timeframeValue.replace(/\s+/g, '');
  const scopeForFilename = data.filters.gameScope.charAt(0).toUpperCase() + data.filters.gameScope.slice(1);
  const dateForFilename = format(new Date(), 'yyyy-MM-dd');
  const filename = `MyStatistics_${scopeForFilename}_${timeframeForFilename}_${dateForFilename}.pdf`;
  
  // Save the PDF
  doc.save(filename);
};