
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfmvvpbpuqbzidptxbqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbXZ2cGJwdXFiemlkcHR4YnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjY3NjEsImV4cCI6MjA2MTIwMjc2MX0.CNRkqP5Rmup3CIGTm1QjSEJZC4PA7FP3RoRgmRebhyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Disable auto URL detection to prevent refresh loops
    flowType: 'pkce' // Use PKCE flow for more security
  }
});

// Utility to handle corrupted tokens or emergency sign out
export const clearAuthState = async () => {
  try {
    await supabase.auth.signOut({ scope: 'local' });
    // Clear any potentially corrupted state
    localStorage.removeItem('supabase.auth.token');
    localStorage.removeItem('supabase.auth.refreshToken');
    console.log("Auth state cleared");
  } catch (e) {
    console.error("Error clearing auth state:", e);
  }
};
